# Docker compose file to manage your deployed images.
# Use mariadb 10.3.32 because it supports ARM devices 
# Use Scada-LTS v2.6.10 war file
# Using attached webapps folder as developer you will be able to modify the static content from host os.
# Attach shell to stop the tomcat instance and then you will be able to run in JPDA mode.
version: '3'
services: 
    database:
        container_name: mariadb
        image: mariadb:10.3.32
        ports:
            - "3306:3306"
        environment: 
            - MYSQL_ROOT_PASSWORD=root
            # - MYSQL_USER=root
            # - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=scadalts
        expose: ["3306"]
        volumes:
            -   ./docker/volumes/databases:/home/
    scadalts:
        container_name: scada
        build:
          context: .
          dockerfile: Dockerfile
        ports: 
            - "8080:8080"
        depends_on: 
            - database
        expose: ["8080", "8000"]
        links:
            - database:database
